In [1]:
import numpy as np


### Задание 1

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
type(a)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis = 0)

In [5]:
mean_a

array([2. , 8.4])

### Задание 2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [7]:
r = np.array([[1, 6],
              [2, 8]])

In [25]:
a_cen = ((r[0,0]*r[0,1])+(r[1,0]*r[1,1]))
a_cen

22

In [10]:
np.dot(r[:,0],r[:,1])

22

In [11]:
a_centered_sp = ((a_centered[0,0]*a_centered[0,1])+(a_centered[1,0]*a_centered[1,1])+(a_centered[2,0]*
                 a_centered[2,1])+(a_centered[3,0]*a_centered[3,1])+(a_centered[4,0]*a_centered[4,1]))/5
a_centered_sp

1.6

In [15]:
np.dot(a_centered[:, 0], a_centered[:, 1])/5

1.6

## Тема "Работа с данными в Pandas"

### Задание 1

In [16]:
import pandas as pd

In [17]:
authors = pd.DataFrame({'author_id': [1, 2, 3],
                        'author_name' : ['Тургенев', 'Чехов', 'Островкий']}, 
                         columns=['author_id', 'author_name'])

In [18]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3   Островкий

In [19]:
authors['author_name'].head()

0     Тургенев
1        Чехов
2    Островкий
Name: author_name, dtype: object

In [20]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3],
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо',
                                    'Толстый и тонкий', 'Дама с собачкой',
                                    'Гроза', ' Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]},
                                    columns=['author_id', 'book_title', 'price'])

In [21]:
book

author_id             book_title  price
0          1            Отцы и дети    450
1          1                  Рудин    300
2          1      Дворянское гнездо    350
3          2       Толстый и тонкий    500
4          2        Дама с собачкой    450
5          3                  Гроза    370
6          3   Таланты и поклонники    290

### Задание 2

In [22]:
author_price = pd.merge(authors, book, on = 'author_id', how = 'left')
author_price

author_id author_name             book_title  price
0          1    Тургенев            Отцы и дети    450
1          1    Тургенев                  Рудин    300
2          1    Тургенев      Дворянское гнездо    350
3          2       Чехов       Толстый и тонкий    500
4          2       Чехов        Дама с собачкой    450
5          3   Островкий                  Гроза    370
6          3   Островкий   Таланты и поклонники    290

### Задание 3

In [23]:
top5 = author_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3   Островкий              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [24]:
authors_stat = author_price.groupby('author_name').agg({'price':['max','min','mean']})
authors_stat.columns = ['_'.join(col).strip() for col in authors_stat.columns.values]
authors_stat.reset_index(inplace=True)
authors_stat

author_name  price_max  price_min  price_mean
0   Островкий        370        290  330.000000
1    Тургенев        450        300  366.666667
2       Чехов        500        450  475.000000